server:
  port: 9998
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:provideaged.db

  #    url: jdbc:mysql://localhost:3306/ProvideAged?useSSL=true&serverTimezone=UTC
  #    username: root
  #    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #正向工程
    show-sql: true #显示SQL